test_that("use", {
  expect_silent(check_folder_name("."))
  expect_silent(check_folder_name("~"))
  expect_silent(check_folder_name("~/"))
  expect_silent(check_folder_name("~/foldername"))
  expect_silent(check_folder_name("~/foldername/sub_foldername"))
  expect_silent(check_folder_name("/home"))
  expect_silent(check_folder_name("/home/"))
  expect_error(check_folder_name(c("/home", "/home")))
  expect_error(check_folder_name(0))
  expect_error(check_folder_name(-1))
  expect_error(check_folder_name(""))
  expect_error(check_folder_name(c()))
  expect_error(check_folder_name(NA))
  expect_error(check_folder_name(NULL))
  expect_error(check_folder_name(Inf))
  expect_error(check_folder_name(42))
  expect_error(check_folder_name(3.14))
})
