test_that("use", {
  expect_silent(check_pheno_model_id("p1"))
  expect_silent(check_pheno_model_id("p2"))
  expect_silent(check_pheno_model_id(""))
  expect_error(check_pheno_model_id(c("p1", "p2")))
  expect_error(check_pheno_model_id("x2"))
  expect_error(check_pheno_model_id(0))
  expect_error(check_pheno_model_id(-1))
  expect_error(check_pheno_model_id("p"))
  expect_error(check_pheno_model_id(c()))
  expect_error(check_pheno_model_id(NA))
  expect_error(check_pheno_model_id(NULL))
  expect_error(check_pheno_model_id(Inf))
  expect_error(check_pheno_model_id(42))
  expect_error(check_pheno_model_id(3.14))
})
