test_that("use", {
  if (!is_gcae_installed()) return()
  expect_silent(check_model(read_model_file(get_gcae_model_filename("M0"))))
  expect_silent(check_model(read_model_file(get_gcae_model_filename("M1"))))
  expect_silent(check_model(read_model_file(get_gcae_model_filename("M3d"))))
  expect_silent(check_model(read_model_file(get_gcae_model_filename("M3e"))))
  expect_silent(check_model(read_model_file(get_gcae_model_filename("M3f"))))
  expect_error(check_model("my_data"))
  expect_error(check_model(c(1, 1)))
  expect_error(check_model(0))
  expect_error(check_model(-1))
  expect_error(check_model(""))
  expect_error(check_model(c()))
  expect_error(check_model(NA))
  expect_error(check_model(NULL))
  expect_error(check_model(Inf))
  expect_error(check_model(42))
  expect_error(check_model(3.14))
})
