test_that("use", {
  expect_silent(check_csv_filename("my.csv"))
  expect_silent(check_csv_filename("~/my.csv"))
  expect_silent(check_csv_filename("/home/me/my.csv"))
  expect_error(check_csv_filename("my.txt"))
  expect_error(check_csv_filename("my file.txt"))
  expect_error(check_csv_filename(c("my.csv", "my.csv")))
  expect_error(check_csv_filename(0))
  expect_error(check_csv_filename(-1))
  expect_error(check_csv_filename(""))
  expect_error(check_csv_filename(c()))
  expect_error(check_csv_filename(NA))
  expect_error(check_csv_filename(NULL))
  expect_error(check_csv_filename(Inf))
  expect_error(check_csv_filename(42))
  expect_error(check_csv_filename(3.14))
})
