test_that("use", {
  expect_silent(check_model_filename("M0.json"))
  expect_silent(check_model_filename("~/M0.json"))
  expect_silent(check_model_filename("/home/me/M2.json"))
  expect_error(check_model_filename("X2.json"))
  expect_error(check_model_filename(c("M0.json", "M0.json")))
  expect_error(check_model_filename("my.txt"))
  expect_error(check_model_filename(0))
  expect_error(check_model_filename(-1))
  expect_error(check_model_filename(""))
  expect_error(check_model_filename(c()))
  expect_error(check_model_filename(NA))
  expect_error(check_model_filename(NULL))
  expect_error(check_model_filename(Inf))
  expect_error(check_model_filename(42))
  expect_error(check_model_filename(3.14))
})
