test_that("use", {
  expect_silent(check_resume_from(42))
  expect_silent(check_resume_from(1))
  expect_silent(check_resume_from(0))
  expect_error(check_resume_from(c(1, 1)))
  expect_error(check_resume_from(-1))
  expect_error(check_resume_from("nonsense"))
  expect_error(check_resume_from(""))
  expect_error(check_resume_from(c()))
  expect_error(check_resume_from(NA))
  expect_error(check_resume_from(NULL))
  expect_error(check_resume_from(Inf))
  expect_error(check_resume_from(3.14))
})
