test_that("use", {
  expect_silent(check_file_extension(".R"))
  expect_silent(check_file_extension(".csv"))
  expect_error(check_file_extension(".."))
  expect_error(check_file_extension("/home"))
  expect_error(check_file_extension("~"))
  expect_error(check_file_extension(c(".R", ".R")))
  expect_error(check_file_extension("."))
  expect_error(check_file_extension(0))
  expect_error(check_file_extension(-1))
  expect_error(check_file_extension(""))
  expect_error(check_file_extension(c()))
  expect_error(check_file_extension(NA))
  expect_error(check_file_extension(NULL))
  expect_error(check_file_extension(Inf))
  expect_error(check_file_extension(42))
  expect_error(check_file_extension(3.14))
})
