test_that("use", {
  expect_silent(check_gif_filename("my.gif"))
  expect_silent(check_gif_filename("~/my.gif"))
  expect_silent(check_gif_filename("/home/me/my.gif"))
  expect_error(check_gif_filename("my.txt"))
  expect_error(check_gif_filename(c("my.gif", "my.gif")))
  expect_error(check_gif_filename(0))
  expect_error(check_gif_filename(-1))
  expect_error(check_gif_filename(""))
  expect_error(check_gif_filename(c()))
  expect_error(check_gif_filename(NA))
  expect_error(check_gif_filename(NULL))
  expect_error(check_gif_filename(Inf))
  expect_error(check_gif_filename(42))
  expect_error(check_gif_filename(3.14))
})
