test_that("use", {
  expect_silent(check_gcae_options_filename("my.csv"))
  expect_silent(check_gcae_options_filename("~/my.csv"))
  expect_silent(check_gcae_options_filename("/home/me/my.csv"))
  expect_error(check_gcae_options_filename("my.txt"))
  expect_error(check_gcae_options_filename(c("my.csv", "my.csv")))
  expect_error(check_gcae_options_filename(0))
  expect_error(check_gcae_options_filename(-1))
  expect_error(check_gcae_options_filename(""))
  expect_error(check_gcae_options_filename(c()))
  expect_error(check_gcae_options_filename(NA))
  expect_error(check_gcae_options_filename(NULL))
  expect_error(check_gcae_options_filename(Inf))
  expect_error(check_gcae_options_filename(42))
  expect_error(check_gcae_options_filename(3.14))
})
