test_that("use", {

  # How to generat all those model names
  if (1 == 2) {
    gcae_options <- create_gcae_options(gcae_folder = "~/GitHubs/gcae")
    model_ids <- get_gcae_model_ids(gcae_options = gcae_options)
    cat(paste0("expect_silent(check_model_filename(\"", model_ids, ".json\"))\n"))
  }

  expect_silent(check_model_filename("M0_1n.json"))
  expect_silent(check_model_filename("M0_2n.json"))
  expect_silent(check_model_filename("M0_3n.json"))
  expect_silent(check_model_filename("M0_4n.json"))
  expect_silent(check_model_filename("M0_5n.json"))
  expect_silent(check_model_filename("M0.json"))
  expect_silent(check_model_filename("M1_1n.json"))
  expect_silent(check_model_filename("M1_2n.json"))
  expect_silent(check_model_filename("M1_3n.json"))
  expect_silent(check_model_filename("M1_4n.json"))
  expect_silent(check_model_filename("M1_5n.json"))
  expect_silent(check_model_filename("M1.json"))
  expect_silent(check_model_filename("M3d_1n.json"))
  expect_silent(check_model_filename("M3d_2n.json"))
  expect_silent(check_model_filename("M3d_3n.json"))
  expect_silent(check_model_filename("M3d_4n.json"))
  expect_silent(check_model_filename("M3d_5n.json"))
  expect_silent(check_model_filename("M3d.json"))
  expect_silent(check_model_filename("M3e_1n.json"))
  expect_silent(check_model_filename("M3e_2n.json"))
  expect_silent(check_model_filename("M3e_3n.json"))
  expect_silent(check_model_filename("M3e_4n.json"))
  expect_silent(check_model_filename("M3e_5n.json"))
  expect_silent(check_model_filename("M3e.json"))
  expect_silent(check_model_filename("M3f_1n.json"))
  expect_silent(check_model_filename("M3f_2n.json"))
  expect_silent(check_model_filename("M3f_3n.json"))
  expect_silent(check_model_filename("M3f_4n.json"))
  expect_silent(check_model_filename("M3f_5n.json"))
  expect_silent(check_model_filename("M3f.json"))
  expect_silent(check_model_filename("M3j10U_1n.json"))
  expect_silent(check_model_filename("M3j10U_2n.json"))
  expect_silent(check_model_filename("M3j10U_3n.json"))
  expect_silent(check_model_filename("M3j10U_4n.json"))
  expect_silent(check_model_filename("M3j10U_5n.json"))
  expect_silent(check_model_filename("M3j10U.json"))
  expect_silent(check_model_filename("M3j10X_1n.json"))
  expect_silent(check_model_filename("M3j10X_2n.json"))
  expect_silent(check_model_filename("M3j10X_3n.json"))
  expect_silent(check_model_filename("M3j10X_4n.json"))
  expect_silent(check_model_filename("M3j10X_5n.json"))
  expect_silent(check_model_filename("M3j10X.json"))
  expect_silent(check_model_filename("M0.json"))
  expect_silent(check_model_filename("~/M0.json"))
  expect_silent(check_model_filename("/home/me/M2.json"))
  expect_error(check_model_filename("X2.json"))
  expect_error(check_model_filename(c("M0.json", "M0.json")))
  expect_error(check_model_filename("my.txt"))
  expect_error(check_model_filename(0))
  expect_error(check_model_filename(-1))
  expect_error(check_model_filename(""))
  expect_error(check_model_filename(c()))
  expect_error(check_model_filename(NA))
  expect_error(check_model_filename(NULL))
  expect_error(check_model_filename(Inf))
  expect_error(check_model_filename(42))
  expect_error(check_model_filename(3.14))
})
