test_that("use", {
  expect_silent(check_superpops(superpops = "some_file"))
  expect_silent(check_superpops("some_file.csv"))
  expect_silent(check_superpops(""))
  expect_error(check_superpops(superpops = "some file"))
  expect_error(check_superpops(1))
  expect_error(check_superpops(c(1, 1)))
  expect_error(check_superpops(0))
  expect_error(check_superpops(-1))
  expect_error(check_superpops(c()))
  expect_error(check_superpops(NA))
  expect_error(check_superpops(NULL))
  expect_error(check_superpops(Inf))
  expect_error(check_superpops(42))
  expect_error(check_superpops(3.14))
})
