test_that("use", {
  expect_silent(check_gcae_setup(create_gcae_setup()))
  expect_error(check_gcae_setup(1))
  expect_error(check_gcae_setup(c(1, 1)))
  expect_error(check_gcae_setup(0))
  expect_error(check_gcae_setup(-1))
  expect_error(check_gcae_setup("nonsense"))
  expect_error(check_gcae_setup(""))
  expect_error(check_gcae_setup(c()))
  expect_error(check_gcae_setup(NA))
  expect_error(check_gcae_setup(NULL))
  expect_error(check_gcae_setup(Inf))
  expect_error(check_gcae_setup(42))
  expect_error(check_gcae_setup(3.14))
})
