test_that("use", {
  expect_silent(check_png_filename("my.png"))
  expect_silent(check_png_filename("~/my.png"))
  expect_silent(check_png_filename("/home/me/my.png"))
  expect_error(check_png_filename("my.txt"))
  expect_error(check_png_filename(c("my.png", "my.png")))
  expect_error(check_png_filename(0))
  expect_error(check_png_filename(-1))
  expect_error(check_png_filename(""))
  expect_error(check_png_filename(c()))
  expect_error(check_png_filename(NA))
  expect_error(check_png_filename(NULL))
  expect_error(check_png_filename(Inf))
  expect_error(check_png_filename(42))
  expect_error(check_png_filename(3.14))
})
