test_that("use", {
  expect_silent(check_n_neurons(42))
  expect_silent(check_n_neurons(1))
  expect_error(check_n_neurons(c(1, 1)))
  expect_error(check_n_neurons(0))
  expect_error(check_n_neurons(-1))
  expect_error(check_n_neurons("nonsense"))
  expect_error(check_n_neurons(""))
  expect_error(check_n_neurons(c()))
  expect_error(check_n_neurons(NA))
  expect_error(check_n_neurons(NULL))
  expect_error(check_n_neurons(Inf))
  expect_error(check_n_neurons(3.14))
})
