test_that("use", {
  expect_silent(check_datadir(datadir = "my_datadir/"))
  expect_error(check_datadir("."))
  expect_error(check_datadir("./"))
  expect_error(check_datadir(datadir = "my_datadir"))
  expect_error(check_datadir(1))
  expect_error(check_datadir(c(1, 1)))
  expect_error(check_datadir(0))
  expect_error(check_datadir(-1))
  expect_error(check_datadir(""))
  expect_error(check_datadir(c()))
  expect_error(check_datadir(NA))
  expect_error(check_datadir(NULL))
  expect_error(check_datadir(Inf))
  expect_error(check_datadir(42))
  expect_error(check_datadir(3.14))
})
