test_that("use", {
  expect_silent(check_epochs(42))
  expect_silent(check_epochs(1))
  expect_silent(check_epochs(0))
  expect_error(check_epochs(c(1, 1)))
  expect_error(check_epochs(-1))
  expect_error(check_epochs("nonsense"))
  expect_error(check_epochs(""))
  expect_error(check_epochs(c()))
  expect_error(check_epochs(NA))
  expect_error(check_epochs(NULL))
  expect_error(check_epochs(Inf))
  expect_error(check_epochs(3.14))
})
