test_that("use", {
  expect_silent(check_save_interval(42))
  expect_silent(check_save_interval(1))
  expect_error(check_save_interval(c(1, 1)))
  expect_error(check_save_interval(0))
  expect_error(check_save_interval(-1))
  expect_error(check_save_interval("nonsense"))
  expect_error(check_save_interval(""))
  expect_error(check_save_interval(c()))
  expect_error(check_save_interval(NA))
  expect_error(check_save_interval(NULL))
  expect_error(check_save_interval(Inf))
  expect_error(check_save_interval(3.14))
})
