on:
  push:
  pull_request:

name: build_singularity

jobs:
  build_singularity:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        singularity_version:
          - '3.7.4'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      #- uses: actions/checkout@v2

      - name: Show singularity version
        run: singularity version

      - name: Show present working directory
        run: echo $PWD

      - name: Clone gcaer
        run: git clone https://github.com/richelbilderbeek/gcaer --depth=1

      - name: Clone GenoCAE
        run: git clone -b Pheno https://github.com/richelbilderbeek/GenoCAE --depth=1

      - name: Go into folder
        run: cd gcaer

      - name: Create Singularity container
        run: ./scripts/build_singularity_container.sh

      - name: Test container, must detect GCAE
        run: singularity test gcaer.sif

      - name: Show help of container
        run: singularity run-help gcaer.sif

      - name: Show run script
        run: cat scripts/run_container.sh

      - name: Show R script
        run: cat scripts/demo_container.R

      - name: Run container
        run: ./scripts/run_container.sh

