on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:

    strategy:
      fail-fast: false
      matrix:
        install_gcae: [true, false]
        os: [ubuntu-latest]

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v1

      #- uses: s-weigand/setup-conda@v1

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install libpoppler-cpp-dev
        run: sudo apt install -qq libpoppler-cpp-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "gifski"))
          remotes::install_github("richelbilderbeek/plinkr")
          install.packages("semver")
          remotes::install_github("richelbilderbeek/ormr")
          remotes::install_github("ropensci/pdftools")
          remotes::install_github("OchoaLab/genio")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
          remotes::install_cran("lintr")
          remotes::install_github("MangoTheCat/goodpractice")
        shell: Rscript {0}

      - name: Install GCAE prerequisistes
        env:
          install_gcae: ${{ matrix.install_gcae }}
        run: if [[ "$install_gcae" == true ]]; then sudo scripts/install_gcae_prerequisites.sh; fi

      - name: Install GCAE using gcaer
        env:
          install_gcae: ${{ matrix.install_gcae }}
        run: if [[ "$install_gcae" == true ]]; then ./scripts/install_gcae.sh; fi

      - name: Install PLINK
        env:
          install_gcae: ${{ matrix.install_gcae }}
        run: if [[ "$install_gcae" == true ]]; then Rscript -e "plinkr::install_plinks()"; fi

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Test coverage (when GCAE is installed)
        env:
          install_gcae: ${{ matrix.install_gcae }}
        run: if [[ "$install_gcae" == true ]]; then Rscript -e "covr::codecov()"; fi

      - name: Lint (when GCAE is not installed)
        env:
          install_gcae: ${{ matrix.install_gcae }}
        run: if [[ "$install_gcae" == false ]]; then Rscript -e "lintr::lint_package()"; fi

#      - name: Install GCAE
#        run: remotes::install_github("richelbilderbeek/gcaer")
#        shell: Rscript {0}

      - name: Report
        run: ./scripts/gcaer_report.sh

#      - name: Self-test
#        env:
#          install_gcae: ${{ matrix.install_gcae }}
#        run: if [[ "$install_gcae" == true ]]; then Rscript -e "gcaer::do_gcae_self_test()"; fi

