# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:

    strategy:
      fail-fast: false
      matrix:
        install_gcae: [true, false]
        os: [ubuntu-latest]

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

#      - name: Install nvidia-cuda-toolkit
#        run: sudo apt install -qq nvidia-cuda-toolkit

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install libpoppler-cpp-dev
        run: sudo apt install -qq libpoppler-cpp-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_github("richelbilderbeek/plinkr")
          install.packages("semver")
          remotes::install_github("richelbilderbeek/ormr")
          remotes::install_github("ropensci/pdftools")
          remotes::install_github("OchoaLab/genio")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
          remotes::install_cran("lintr")
          remotes::install_github("MangoTheCat/goodpractice")
        shell: Rscript {0}

      - name: Install GCAE
        env:
          install_gcae: ${{ matrix.install_gcae }}
        run: if [[ "$install_gcae" == true ]]; then ./scripts/install_gcae.sh; fi

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Test coverage
        env:
          install_gcae: ${{ matrix.install_gcae }}
        run: if [[ "$install_gcae" == true ]]; then Rscript -e "covr::codecov()"; fi

      - name: Lint
        run: lintr::lint_package()
        shell: Rscript {0}

#      - name: Install GCAE
#        run: remotes::install_github("richelbilderbeek/gcaer")
#        shell: Rscript {0}

#      - name: Report
#        run: gcaer::gcaer_report()
#        shell: Rscript {0}

#      - name: Self-test
#        env:
#          install_gcae: ${{ matrix.install_gcae }}
#        run: if [[ "$install_gcae" == true ]]; then Rscript -e "gcaer::do_gcae_self_test()"; fi

